import type { Check, Result } from "../contracts";

export type CollectionStage = "disabled" | "inspection" | "editing" | "publication";
export type SourceMode = "legacy" | "database";
export type CollectionState = "draft" | "submitted" | "approved" |
  "changes_requested" | "rejected" | "published" | "superseded" | "discarded";
export type CollectionBase = { publicationId: string | null; digest: string };
export type Member = { recipeId: string; recipeSlug: string; contentVersion: number;
  reviewDigest: string; tagsDigest: string; placementNote: string;
  fit: "unverified" | "accepted" | "blocked" };
export type CollectionSnapshot = {
  collectionId: string; slug: string; title: string; tagline: string; story: string;
  forWhen: string; refresh: string; shelf: string; sortOrder: number;
  stage: { min: number | null; max: number | null };
  series: { key: string; volume: number } | null;
  listingState: "listed" | "unlisted" | "retired";
  availability: "open" | "coming-soon"; cloth: string;
  cover: { src: string; width: number; height: number; alt: string; assetDigest: string } | null;
  members: Member[];
};
export type CollectionRevision = { id: string; collectionId: string; version: number;
  digest: string; base: CollectionBase; state: CollectionState;
  submissionId: string | null; snapshot: CollectionSnapshot; savedAt: string; savedBy: string };
export type CollectionImpact = { token: string; checkedAt: string; sourceRevision: string;
  protectedRecipeIds: string[]; eligibleBuyerCount: number; pendingLiveCount: number;
  offerIds: string[]; affectedCampaignSlugs: string[]; checks: Check[] };
export type CollectionReadiness = { digest: string; checks: Check[];
  readyForApproval: boolean; readyToPublish: boolean; needsVerification: boolean };
export type CollectionReceipt = { operationId: string; collectionId: string;
  revisionId: string; publicationId: string | null; releaseId: string | null;
  version: number; digest: string; noChange: boolean; committedAt: string;
  refreshState: "complete" | "pending" };
export type CollectionReceiptLog = { base: CollectionBase; receipts: CollectionReceipt[] };
export type CollectionCommand = { collectionId: string; operationId: string; reason: string };
export type SaveCollectionCommand = CollectionCommand & { expectedVersion: number;
  expectedDigest: string; base: CollectionBase; snapshot: CollectionSnapshot;
  reopenReviewed: boolean };
export type SubmitCollectionCommand = CollectionCommand & { revisionId: string; expectedVersion: number;
  expectedDigest: string; impactToken: string };
export type IssueCollectionCommand = CollectionCommand & { revisionId: string; expectedVersion: number;
  expectedDigest: string; code: string; field: string | null; severity: "blocker" | "suggestion"; explanation: string };
export type ReviewCollectionCommand = SubmitCollectionCommand & { submissionId: string;
  decision: "approve" | "changes_requested" | "reject"; resolvedIssueIds: string[] };
export type AccessDecision = { releaseId: string; sourceKind: string; policy: "additions-v1" | "original-only" };
export type UndecidedAccess = { releaseId: string; version: number; sourceKind: string; buyers: number };
export type PublishCollectionCommand = CollectionCommand & { revisionId: string;
  expectedVersion: number; expectedDigest: string; base: CollectionBase;
  impactToken: string; approveNow: boolean; accessDecisions: AccessDecision[] };
export type CollectionStatusFilter = "published" | "unpublished" | "listed" | "unlisted" | "retired";
export type CollectionQuery = { q: string; shelf: string[]; stage: string[];
  status: CollectionStatusFilter[]; draft: boolean | null; attention: boolean; page: number; pageSize: 25 };
export type CollectionEvent = { id: string; action: string; at: string; reason: string;
  humanAuthoriser: string | null; authoriserEmail: string | null; executor: string; executorType: "human" | "operator";
  beforeRef: string | null; afterRef: string | null; operationId: string };
export type ReviewIssue = { id: string; code: string; field: string | null; severity: "blocker" | "suggestion";
  origin: "human" | "validation" | "source" | "import" | "ai"; explanation: string; raisedBy: string | null;
  raisedAt: string; resolved: boolean };
export type ReviewDecision = { id: string; decision: "approve" | "changes_requested" | "reject"; reason: string;
  decidedAt: string; decidedBy: string | null; revisionId: string; version: number; digest: string };
export type CollectionReview = {
  submission: { id: string; submittedAt: string; submittedBy: string | null; reason: string } | null;
  issues: ReviewIssue[]; decisions: ReviewDecision[] };
export type RecipeSummary = { recipeId: string; slug: string; title: string; publication: string;
  totalMinutes: number | null; imagePath: string; allergens: string[]; storageNotes: string | null };
export type CollectionDetail = { collectionId: string; identity: { slug: string; title: string };
  sourceMode: SourceMode; commerceState: CollectionRow["commerceState"];
  published: { publicationId: string; releaseId: string | null; snapshot: CollectionSnapshot } | null;
  working: CollectionRevision | null; readiness: CollectionReadiness;
  impact: Result<CollectionImpact>; review: CollectionReview; recipes: RecipeSummary[];
  history: CollectionEvent[]; historyCursor: string | null; checkedAt: string };
export type CollectionHistoryPage = { events: CollectionEvent[]; nextCursor: string | null };
export type CollectionRow = { collectionId: string; slug: string; title: string;
  shelf: string; stage: CollectionSnapshot["stage"]; series: CollectionSnapshot["series"];
  listingState: CollectionSnapshot["listingState"]; availability: CollectionSnapshot["availability"];
  publicationId: string | null; publishedCount: number; draftCount: number | null;
  workingState: CollectionState | null; needsAttention: boolean;
  commerceState: "enabled" | "disabled" | "no_offer" | "unavailable"; changedAt: string };
export type CollectionLibrary = { rows: CollectionRow[]; filteredTotal: number;
  page: number; pageSize: 25; checkedAt: string };
export type SnapshotChange = { field: string; before: unknown; after: unknown };
export type DraftControl = CollectionCommand & { action: "rebase" | "copy_publication" | "discard";
  expectedDigest: string; referenceId: string | null };
export type DraftResult = { operationId: string; noChange: boolean; revision: CollectionRevision | null; committedAt: string;
  issueId?: string; decisionId?: string };
export type CatalogRecipe = { recipeId: string; slug: string; title: string; publication: string;
  contentVersion: number | null; activeHash: string | null; reviewed: boolean; allergens: string[];
  tagsDigest: string; totalMinutes: number | null; mealLabels: string[]; dietLabels: string[] };
export type CatalogPage = { rows: CatalogRecipe[]; filteredTotal: number; page: number; pageSize: 25; checkedAt: string };
export type CoverAsset = NonNullable<CollectionSnapshot["cover"]>;
