import type { Check, Result } from "../contracts";

export type CollectionStage = "disabled" | "inspection" | "editing" | "publication";
export type SourceMode = "legacy" | "database";
export type CollectionState = "draft" | "submitted" | "approved" |
  "changes_requested" | "rejected" | "published" | "superseded" | "discarded";
export type CollectionBase = { publicationId: string | null; digest: string };
export type Member = { recipeId: string; recipeSlug: string; contentVersion: number;
  reviewDigest: string; tagsDigest: string; placementNote: string;
  fit: "unverified" | "accepted" | "blocked" };
export type CollectionSnapshot = {
  collectionId: string; slug: string; title: string; tagline: string; story: string;
  forWhen: string; refresh: string; shelf: string; sortOrder: number;
  stage: { min: number | null; max: number | null };
  series: { key: string; volume: number } | null;
  listingState: "listed" | "unlisted" | "retired";
  availability: "open" | "coming-soon"; cloth: string;
  cover: { src: string; width: number; height: number; alt: string; assetDigest: string } | null;
  members: Member[];
};
export type CollectionRevision = { id: string; collectionId: string; version: number;
  digest: string; base: CollectionBase; state: CollectionState;
  submissionId: string | null; snapshot: CollectionSnapshot; savedAt: string; savedBy: string };
export type CollectionImpact = { token: string; checkedAt: string; sourceRevision: string;
  protectedRecipeIds: string[]; eligibleBuyerCount: number; pendingLiveCount: number;
  offerIds: string[]; affectedCampaignSlugs: string[]; checks: Check[] };
export type CollectionReadiness = { digest: string; checks: Check[];
  readyForApproval: boolean; readyToPublish: boolean; needsVerification: boolean };
export type CollectionReceipt = { operationId: string; collectionId: string;
  revisionId: string; publicationId: string | null; releaseId: string | null;
  version: number; digest: string; noChange: boolean; committedAt: string;
  refreshState: "complete" | "pending" };
export type CollectionCommand = { collectionId: string; operationId: string; reason: string };
export type SaveCollectionCommand = CollectionCommand & { expectedVersion: number;
  expectedDigest: string; base: CollectionBase; snapshot: CollectionSnapshot;
  reopenReviewed: boolean };
export type ReviewCollectionCommand = CollectionCommand & { revisionId: string;
  expectedVersion: number; expectedDigest: string; impactToken: string;
  decision: "approve" | "changes_requested" | "reject"; resolvedIssueIds: string[] };
export type PublishCollectionCommand = CollectionCommand & { revisionId: string;
  expectedVersion: number; expectedDigest: string; base: CollectionBase;
  impactToken: string; approveNow: boolean };
export type CollectionStatusFilter = "published" | "unpublished" | "listed" | "unlisted" | "retired";
export type CollectionQuery = { q: string; shelf: string[]; stage: string[];
  status: CollectionStatusFilter[]; draft: boolean | null; attention: boolean; page: number; pageSize: 25 };
export type CollectionEvent = { id: string; action: string; at: string; reason: string;
  humanAuthoriser: string | null; executor: string; executorType: "human" | "operator";
  beforeRef: string | null; afterRef: string | null; operationId: string };
export type CollectionDetail = { collectionId: string; sourceMode: SourceMode;
  published: { publicationId: string; releaseId: string | null; snapshot: CollectionSnapshot } | null;
  working: CollectionRevision | null; readiness: CollectionReadiness;
  impact: Result<CollectionImpact>; history: CollectionEvent[] };
export type CollectionRow = { collectionId: string; slug: string; title: string;
  shelf: string; stage: CollectionSnapshot["stage"]; series: CollectionSnapshot["series"];
  listingState: CollectionSnapshot["listingState"]; availability: CollectionSnapshot["availability"];
  publicationId: string | null; publishedCount: number; draftCount: number | null;
  workingState: CollectionState | null; needsAttention: boolean;
  commerceState: "enabled" | "disabled" | "no_offer" | "unavailable"; changedAt: string };
export type CollectionLibrary = { rows: CollectionRow[]; filteredTotal: number;
  page: number; pageSize: 25; checkedAt: string };
export type SnapshotChange = { field: string; before: unknown; after: unknown };
