import type { Json } from "@/lib/types/database";
export type AdminRole = "owner" | "viewer" | "editor" | "reviewer" | "publisher";
export type Permission = "recipe.read" | "recipe.edit" | "recipe.review"
  | "recipe.publish" | "recipe.withdraw" | "recipe.emergency_withdraw" | "team.manage";
export type ConsoleStage = "disabled" | "inspection" | "editing" | "publication";
export type AdminCode = "AUTH_REQUIRED" | "MFA_REQUIRED" | "DENIED" | "DISABLED"
  | "INVALID" | "NOT_FOUND" | "CONFLICT" | "UNAVAILABLE" | "BLOCKED";
export type Result<T> = { ok: true; value: T }
  | { ok: false; code: AdminCode; reference: string; fields?: Record<string, string> };
export type Operator = { id: string; email: string; roles: AdminRole[]; permissions: Permission[] };
export type AdminContext = { stage: ConsoleStage; operator: Operator; assurance: "aal1" | "aal2" };
export type ContextResult = Result<AdminContext>;
export type PublicationState = "draft" | "published" | "withdrawn";
export type ReviewState = "unreviewed" | "submitted" | "approved" | "changes_requested" | "rejected";
export type LibraryView = "all" | "attention" | "awaiting_review" | "ready" | "published" | "withdrawn";
export type LibraryQuery = { q: string; collections: string[]; publication: PublicationState[];
  review: ReviewState[]; view: LibraryView; page: number; pageSize: 25 };
export type Check = { code: string; scope: string; state: "pass" | "fail" | "unknown";
  severity: "blocker" | "suggestion"; explanation: string; origin: "validation" | "human" | "source" };
export type Readiness = { targetDigest: string; review: ReviewState; checks: Check[];
  needsAttention: boolean; awaitingReview: boolean; readyToPublish: boolean;
  needsVerification: boolean; evaluatedAt: string };
export type RecipeSnapshot = { recipeId: string; slug: string;
  catalog: { title: string; publicSummary: string; totalMinutes: number | null;
    mealLabels: string[]; dietLabels: string[] };
  body: null | { ingredients: Json; instructions: Json; yield: string;
    yieldStructured: Json; reviewedNotes: string | null;
    allergenReviewState: "unknown" | "reviewed_listed" | "reviewed_no_allergens";
    allergens: string[] | null; storageNotes: string | null };
  image: { path: string; alt: string | null; description: string | null;
    objectId: string | null; objectVersion: string | null } };
export type Base = { contentVersion: number | null; activeHash: string };
export type Revision = { id: string; draftId: string; recipeId: string; version: number;
  digest: string; base: Base; state: "draft" | "submitted" | "approved" | "changes_requested"
    | "rejected" | "published" | "superseded"; submissionId: string | null;
  snapshot: RecipeSnapshot; savedAt: string; savedBy: string };
export type Usage = { checkedAt: string; sourceRevision: string | null;
  freeSlots: number[];
  releases: { id: string; collectionId: string; title: string; version: number; state: string;
    sealed: boolean; liveOffer: boolean; pendingLiveAttempt: boolean;
    historicalLivePayment: boolean; testActivity: boolean }[];
  campaigns: { slug: string; status: "draft" | "published"; recipeSlugs: string[];
    promisedCount: number; deploymentRevision: string | null }[] };
export type RecipeRow = { id: string; slug: string; title: string; imagePath: string;
  publication: PublicationState; readiness: Readiness;
  collections: { id: string; title: string }[]; changedAt: string };
export type LibraryResult = { rows: RecipeRow[]; filteredTotal: number;
  summary: Record<LibraryView, number>; query: LibraryQuery; sourceRevision: string;
  checkedAt: string; dependencyChecks: Check[] };
export type AuditEvent = { id: string; actorId: string; action: string; recipeId: string | null;
  revisionId: string | null; digest: string | null; beforeRef: string | null;
  afterRef: string | null; requestId: string; at: string; reason: string | null; result: string };
export type HistoryPage = { events: AuditEvent[]; nextCursor: string | null };
export type LegacyReview = { id: string; contentVersion: number; reviewerKind: string;
  reviewer: string; verdict: string; openBlockers: number; reviewedAt: string };
export type RecipeDetail = { active: RecipeSnapshot; publication: PublicationState;
  contentVersion: number | null; activeHash: string; working: Revision | null;
  readiness: Readiness; usage: Result<Usage>; legacyReviews: LegacyReview[];
  history: HistoryPage; checkedAt: string };
export type StaffMatch = { userId: string; email: string };
export type StaffRow = StaffMatch & { roles: AdminRole[]; active: boolean;
  grantedBy: string; grantedAt: string; revokedBy: string | null; revokedAt: string | null };
export type Asset = { objectId: string; objectVersion: string; path: string; bucket: "recipe-images";
  available: boolean; provenance: "recorded_approval" | "requires_review" };
export type Operation = { operationId: string; recipeId: string; reason: string };
export type DraftCommand = Operation & { expectedVersion: number; expectedDigest: string;
  base: Base; snapshot: RecipeSnapshot; reopenReviewed: boolean };
export type MutationReceipt = { operationId: string; recipeId: string;
  revisionId: string | null; version: number; digest: string; noChange: boolean;
  committedAt: string; publication: PublicationState };
export type ReviewCommand = Operation & { revisionId: string; expectedVersion: number;
  expectedDigest: string; submissionId: string; decision: "approve" | "changes_requested" | "reject";
  resolvedIssueIds: string[] };
export type PublishCommand = Operation & { revisionId: string; expectedVersion: number;
  expectedDigest: string; base: Base; impactToken: string };
export type WithdrawCommand = Operation & { base: Base; impactToken: string;
  emergency: boolean; acknowledgePromiseImpact: boolean };
export type RefreshReceipt = { operationId: string; state: "complete" | "pending" };
