import { PHOTO_BASE, RECIPE_SNAPSHOT } from "@/config/recipe-snapshot";
import type { CollectionRecipe, SeriesKey, ShelfKey, ShowroomCollection } from "@/lib/collections/types";

/**
 * Every collection on the bookcase (/collections), in shelf order. The list,
 * shelves and series come from docs/implementation/recipe-collections/
 * COLLECTIONS.md; each collection's recipes from recipe-tags.json.
 *
 * Collections with 8-12 recipes are "open": they have a page, with a PLACEHOLDER
 * price and "Opening soon" until a commerce offer exists for the slug (plan
 * RC-01 to RC-05). The rest are "coming-soon": they stand on the shelf greyed
 * out and have no page. Halloween, Meal Prep and Protein Packs are also the
 * chapters of the first showroom, /collections/test.
 *
 * Recipe facts are a catalog snapshot (src/config/recipe-snapshot.ts). The
 * recipes are drafts in the catalog, so they carry no link until published.
 * On 2026-10-05 seven adult recipes (written for pregnancy, no child steps)
 * were swapped out of the live books; those recipes were then rewritten for
 * children (RECIPE-TAGS.md).
 */

function recipes(slugs: readonly string[]): CollectionRecipe[] {
  return slugs.map((slug) => {
    const fact = RECIPE_SNAPSHOT[slug];
    if (!fact) throw new Error(`[collections] Unknown recipe in config: ${slug}`);
    return { ...fact, slug, image: `${PHOTO_BASE}${fact.image}` };
  });
}

function cover(slug: string, height: number, alt: string): ShowroomCollection["cover"] {
  return { src: `/images/collections/cover-${slug}-1040.webp`, width: 1040, height, alt };
}

export const SHELVES: readonly { key: ShelfKey; title: string }[] = [
  { key: "mornings", title: "Mornings" },
  { key: "everyday-meals", title: "Everyday meals" },
  { key: "cook-once", title: "Cook once" },
  { key: "nourish", title: "Nourish" },
  { key: "snacks-and-treats", title: "Snacks & treats" },
  { key: "seasons-and-parties", title: "Seasons & parties" },
];

export const SERIES: Record<SeriesKey, { title: string; heading: string; lede: string; bundlePrice: string | null }> = {
  breakfast: {
    title: "Breakfast series",
    heading: "Breakfast, from first bites to big kids",
    lede: "Three volumes that grow with your child.",
    // PLACEHOLDER bundle price (concept, 2026-10-06).
    bundlePrice: "$19.99",
  },
  "meal-prep": {
    title: "Meal Prep series",
    heading: "Cook once, from first purées to family dinners",
    lede: "Three volumes of make-ahead food that grow with your child.",
    bundlePrice: null,
  },
};

const BABY = { min: 6, max: 12 };
const TODDLER = { min: 12, max: 24 };
const KID = { min: 24, max: 48 };
const ALL_STAGES = { min: null, max: null };

export const SHOWROOM_COLLECTIONS: readonly ShowroomCollection[] = [
  // ---------- Mornings: the Breakfast series ----------
  {
    slug: "first-breakfasts",
    status: "published",
    availability: "coming-soon",
    shelf: "mornings",
    stage: BABY,
    series: { key: "breakfast", volume: 1 },
    title: "First Breakfasts",
    tagline: "Soft pancakes, oat fingers and fruit for the first mornings.",
    story: "",
    forWhen: "",
    cloth: "ochre",
    cover: cover("first-breakfasts", 1412, "An ochre cloth cookbook with gold-foil oat fingers on a plate and two blueberries on its cover"),
    refresh: "",
    placeholderPrice: "$7.99",
    recipes: recipes(["asian-pear-rice-congee-pure", "banana-avocado-breakfast-pure-with-yogurt", "spinach-and-feta-egg-muffins"]),
  },
  {
    slug: "toddler-breakfasts",
    status: "published",
    availability: "coming-soon",
    shelf: "mornings",
    stage: TODDLER,
    series: { key: "breakfast", volume: 2 },
    title: "Toddler Breakfasts",
    tagline: "Breakfasts they can hold, made ahead.",
    story: "",
    forWhen: "",
    cloth: "ochre",
    cover: cover("toddler-breakfasts", 1412, "An ochre cloth cookbook with a gold-foil round waffle and blueberries on its cover"),
    refresh: "",
    placeholderPrice: "$7.99",
    recipes: recipes([
      "overnight-oats-with-chia-and-berries",
      "spinach-and-feta-egg-muffins",
      "apple-cinnamon-oat-toddler-porridge",
      "banana-peanut-butter-chia-pudding",
      "veggie-lentil-pancakes",
      "mango-lassi-chia-pudding-cups",
    ]),
  },
  {
    slug: "big-kid-breakfasts",
    status: "published",
    availability: "coming-soon",
    shelf: "mornings",
    stage: KID,
    series: { key: "breakfast", volume: 3 },
    title: "Big-Kid Breakfasts",
    tagline: "Fuller, faster school-morning breakfasts.",
    story: "",
    forWhen: "",
    cloth: "ochre",
    cover: cover("big-kid-breakfasts", 1412, "An ochre cloth cookbook with a gold-foil stack of pancakes topped with blueberries on its cover"),
    refresh: "",
    placeholderPrice: "$7.99",
    recipes: recipes([
      "greek-yogurt-parfait-with-berries-and-almonds",
      "overnight-oats-with-chia-and-berries",
      "spinach-and-feta-egg-muffins",
      "banana-peanut-butter-chia-pudding",
    ]),
  },

  // ---------- Everyday meals ----------
  {
    slug: "first-tastes",
    status: "published",
    availability: "open",
    shelf: "everyday-meals",
    stage: { min: 6, max: 8 },
    title: "First Tastes",
    tagline: "Smooth first spoonfuls, one new flavour at a time.",
    story:
      "Eight simple purées for the first weeks of solids: fruit, vegetables, rice and lentils, blended smooth and sieved for the youngest babies. Short ingredient lists, no added salt or sugar.",
    forWhen: "For the week the high chair arrives and every spoonful is new.",
    cloth: "sage",
    cover: cover("first-tastes", 1415, "A sage-green cloth cookbook with a gold-foil baby spoon, a bowl of purée, a pear and a carrot on its cover"),
    refresh: "New first tastes join through the year.",
    placeholderPrice: "$9.99",
    recipes: recipes([
      "silky-carrot-apple-starter-pure",
      "apple-prune-fiber-friendly-pure",
      "asian-pear-rice-congee-pure",
      "banana-avocado-breakfast-pure-with-yogurt",
      "comforting-sweet-potato-lentil-khichdi-pure",
      "indian-rice-mung-dal-spinach-pure",
      "mediterranean-red-lentil-carrot-pure",
      "zucchini-chickpea-mediterranean-pure",
    ]),
  },
  {
    slug: "first-finger-foods",
    status: "published",
    availability: "open",
    shelf: "everyday-meals",
    stage: { min: 9, max: 12 },
    title: "First Finger Foods",
    tagline: "Soft food babies can pick up themselves.",
    story:
      "Strips, fritters, cakes and soft bites shaped for a baby's grip, with a cutting note for each age. Every one is soft enough to squash between your fingers.",
    forWhen: "For when your baby grabs the spoon and wants to do it alone.",
    cloth: "terracotta",
    cover: cover("first-finger-foods", 1412, "A terracotta cloth cookbook with a gold-foil plate of soft finger strips, fritters and a baby spoon on its cover"),
    refresh: "New finger foods join through the year.",
    placeholderPrice: "$9.99",
    recipes: recipes([
      "avocado-and-black-bean-quesadilla-strips",
      "cheesy-broccoli-and-quinoa-bites",
      "mild-curried-red-lentil-cakes",
      "mini-turkey-and-apple-meatloaf-muffins",
      "pumpkin-and-ricotta-gnocchi-pillows",
      "sesame-tofu-and-veggie-cubes",
      "zucchini-and-feta-fritters",
      "salmon-and-sweet-potato-bowl-with-avocado",
    ]),
  },
  {
    slug: "lunchbox-and-daycare",
    status: "published",
    availability: "open",
    shelf: "everyday-meals",
    stage: KID,
    title: "Lunchbox & Daycare",
    tagline: "Lunches that travel. No nuts.",
    story:
      "Strips, muffins, wraps and bento boxes that taste good cold and pack flat. Every recipe is nut-free, for daycares that ban nuts.",
    forWhen: "For the 7am scramble before drop-off.",
    cloth: "navy",
    cover: cover("lunchbox-and-daycare", 1402, "A navy cloth cookbook with a gold-foil bento lunchbox and a small thermos on its cover"),
    refresh: "New lunches join before each school term.",
    placeholderPrice: "$12.99",
    recipes: recipes([
      "avocado-and-black-bean-quesadilla-strips",
      "zucchini-and-feta-fritters",
      "mediterranean-chicken-and-chickpea-salad",
      "baked-samosa-puffs",
      "mini-baked-chicken-nuggets",
      "onigiri-rice-triangles",
      "savory-corn-and-cheddar-muffins",
      "spinach-and-cheese-pizza-scrolls",
      "turkey-and-hummus-pinwheels",
      "greek-pita-bento-box",
      "mini-bean-and-cheese-burritos",
      "creamy-hummus-yogurt-veggie-dippers",
    ]),
  },
  {
    slug: "picky-eater-favorites",
    status: "published",
    availability: "open",
    shelf: "everyday-meals",
    stage: KID,
    title: "Picky Eater Favorites",
    tagline: "Gentle wins for the “won't eat it” years.",
    story:
      "Nuggets, fries, pizza scrolls and quesadillas, with vegetables tucked inside and dips on the side. Familiar shapes first, new flavours after.",
    forWhen: "For the plate that comes back with only the bread eaten.",
    cloth: "rose",
    cover: cover("picky-eater-favorites", 1418, "A dusty-rose cloth cookbook with a gold-foil child's plate of broccoli, fries and a dip on its cover"),
    refresh: "New favourites join through the year.",
    placeholderPrice: "$12.99",
    recipes: recipes([
      "mini-baked-chicken-nuggets",
      "cinnamon-sweet-potato-snack-fries-with-yogurt-dip",
      "spinach-and-cheese-pizza-scrolls",
      "avocado-and-black-bean-quesadilla-strips",
      "mini-bean-and-cheese-burritos",
      "veggie-packed-lasagna",
      "turkey-veggie-mini-meatballs-with-pasta",
      "cheesy-veggie-quinoa-toddler-bites",
      "cheesy-veggie-mini-muffins",
      "creamy-hummus-yogurt-veggie-dippers",
      "deconstructed-soft-taco-toddler-bowl",
      "veggie-rice-snack-fritters",
    ]),
  },
  {
    slug: "family-dinners",
    status: "published",
    availability: "open",
    shelf: "everyday-meals",
    stage: ALL_STAGES,
    title: "Family Dinners",
    tagline: "One dinner for everyone, with a portion for the smallest.",
    story:
      "Curries, stews, tacos and pasta the whole table eats. Each recipe says how to purée, mash or cut the little one's portion, and takes it out before the salt goes in.",
    forWhen: "For the night you refuse to cook twice.",
    cloth: "walnut",
    cover: cover("family-dinners", 1413, "A walnut-brown cloth cookbook with a gold-foil casserole pot, a ladle and three spoons on its cover"),
    refresh: "New family dinners join each season.",
    placeholderPrice: "$12.99",
    recipes: recipes([
      "mild-vegetable-curry-with-rice",
      "one-pot-chicken-and-vegetable-rice",
      "slow-cooker-beef-and-vegetable-stew",
      "vegetable-noodle-soup",
      "baked-fish-tacos-with-slaw",
      "tofu-and-vegetable-stir-fry",
      "vegetable-pasta-primavera",
      "bean-and-veggie-burrito-bowl",
      "mediterranean-baked-chicken-with-quinoa",
      "veggie-packed-lasagna",
      "chicken-and-vegetable-stir-fry-with-brown-rice",
      "turkey-veggie-mini-meatballs-with-pasta",
    ]),
  },

  // ---------- Cook once: the Meal Prep series ----------
  {
    slug: "batch-and-freeze-for-babies",
    status: "published",
    availability: "open",
    shelf: "cook-once",
    stage: BABY,
    series: { key: "meal-prep", volume: 1 },
    title: "Batch & Freeze for Babies",
    tagline: "One afternoon of cooking, a freezer full of baby meals.",
    story:
      "Purées and mashes that freeze in ice-cube trays: fruit, vegetables, lentils, chicken and beef. Thaw two cubes and a meal is ready.",
    forWhen: "For the parent who would rather cook once than every night.",
    cloth: "forest",
    cover: cover("batch-and-freeze-for-babies", 1414, "A forest-green cloth cookbook with a gold-foil ice-cube tray of purée, a snowflake and a spoon on its cover"),
    refresh: "New freezer recipes join each season.",
    placeholderPrice: "$9.99",
    recipes: recipes([
      "silky-carrot-apple-starter-pure",
      "apple-prune-fiber-friendly-pure",
      "asian-pear-rice-congee-pure",
      "comforting-sweet-potato-lentil-khichdi-pure",
      "indian-rice-mung-dal-spinach-pure",
      "mediterranean-red-lentil-carrot-pure",
      "zucchini-chickpea-mediterranean-pure",
      "mild-mexican-black-bean-sweet-corn-pure",
      "italian-tomato-vegetable-pure-with-tiny-pasta",
      "lentil-and-vegetable-curry-with-coconut-milk",
      "one-pot-chicken-and-vegetable-rice",
      "slow-cooker-beef-and-vegetable-stew",
    ]),
  },
  {
    slug: "meal-prep",
    status: "published",
    availability: "open",
    inShowroom: true,
    shelf: "cook-once",
    stage: TODDLER,
    series: { key: "meal-prep", volume: 2 },
    title: "Meal Prep",
    tagline: "Cook once on Sunday. Eat well on Wednesday.",
    story:
      "Ten recipes that keep: a slow-cooker stew, a lasagna, a vegetable curry, and muffins, bites and burritos that go from freezer to plate on a tired evening. Every one of them freezes.",
    forWhen: "For the evenings when the only plan is the one you made at the weekend.",
    cloth: "forest",
    cover: cover("meal-prep", 1400, "A forest-green cloth cookbook with gold-foil stacked food containers on its cover"),
    refresh: "New make-ahead recipes join each season.",
    placeholderPrice: "$12.99",
    recipes: recipes([
      "slow-cooker-beef-and-vegetable-stew",
      "veggie-packed-lasagna",
      "mild-vegetable-curry-with-rice",
      "mini-turkey-and-apple-meatloaf-muffins",
      "one-pot-chicken-and-vegetable-rice",
      "cheesy-veggie-quinoa-toddler-bites",
      "cheesy-broccoli-and-quinoa-bites",
      "mini-bean-and-cheese-burritos",
      "veggie-lentil-pancakes",
      "cheesy-veggie-mini-muffins",
    ]),
  },
  {
    slug: "freezer-dinners",
    status: "published",
    availability: "open",
    shelf: "cook-once",
    stage: KID,
    series: { key: "meal-prep", volume: 3 },
    title: "Freezer Dinners",
    tagline: "Batch, freeze, reheat on the busy nights.",
    story:
      "Curries, soups, a lasagna and rice bowls that freeze for up to three months and reheat well. Cook at the weekend, and dinner on a Wednesday takes ten minutes.",
    forWhen: "For the nights when there's no time to cook and no appetite for takeout.",
    cloth: "forest",
    cover: cover("freezer-dinners", 1412, "A forest-green cloth cookbook with a gold-foil lasagna dish, a ladle and a snowflake on its cover"),
    refresh: "New freezer dinners join each season.",
    placeholderPrice: "$12.99",
    recipes: recipes([
      "veggie-packed-lasagna",
      "mild-vegetable-curry-with-rice",
      "lentil-and-vegetable-curry-with-coconut-milk",
      "folate-rich-lentil-and-spinach-soup",
      "slow-cooker-beef-and-vegetable-stew",
      "one-pot-chicken-and-vegetable-rice",
      "soft-chicken-veggie-rice-bowl",
      "mediterranean-baked-chicken-with-quinoa",
    ]),
  },

  // ---------- Nourish ----------
  {
    slug: "iron-rich-first-foods",
    status: "published",
    availability: "open",
    shelf: "nourish",
    stage: BABY,
    title: "Iron-Rich First Foods",
    tagline: "Iron for growing babies, paired with vitamin C.",
    story:
      "Lentils, beans, beef and spinach, cooked soft and paired with tomato, lemon or sweet potato, which help the iron absorb. Purées first, then mashes and bowls.",
    forWhen: "For the six-month check-up when the doctor mentions iron.",
    cloth: "slate",
    cover: cover("iron-rich-first-foods", 1385, "A slate-blue cloth cookbook with a gold-foil bowl of lentils, spinach leaves and a halved lemon on its cover"),
    refresh: "New iron-rich recipes join through the year.",
    placeholderPrice: "$9.99",
    recipes: recipes([
      "comforting-sweet-potato-lentil-khichdi-pure",
      "indian-rice-mung-dal-spinach-pure",
      "mediterranean-red-lentil-carrot-pure",
      "zucchini-chickpea-mediterranean-pure",
      "mild-mexican-black-bean-sweet-corn-pure",
      "slow-cooker-beef-and-vegetable-stew",
      "folate-rich-lentil-and-spinach-soup",
      "baked-sweet-potato-with-black-beans-and-avocado",
      "bean-and-veggie-burrito-bowl",
      "mild-curried-red-lentil-cakes",
    ]),
  },
  {
    slug: "protein-packs",
    status: "published",
    availability: "open",
    inShowroom: true,
    shelf: "nourish",
    stage: TODDLER,
    title: "Protein Packs",
    tagline: "Meals built around one protein, in shapes little hands can manage.",
    story:
      "Chicken, salmon, tuna, red lentils, tofu, turkey and black beans. Each recipe is built around one of them and comes as a bite, a cake, a bowl or a pinwheel.",
    forWhen: "For the plate that keeps coming back with only the pasta eaten.",
    cloth: "plum",
    cover: cover("protein-packs", 1422, "A plum cloth cookbook with a gold-foil fish on a plate, a bowl of lentils, beans and tofu cubes on its cover"),
    refresh: "New recipes join through the year.",
    placeholderPrice: "$12.99",
    recipes: recipes([
      "mini-baked-chicken-nuggets",
      "onigiri-rice-triangles",
      "soft-chicken-veggie-rice-bowl",
      "mild-curried-red-lentil-cakes",
      "sesame-tofu-and-veggie-cubes",
      "turkey-and-hummus-pinwheels",
      "bean-and-veggie-burrito-bowl",
      "salmon-potato-veggie-mash",
      "soft-tofu-veggie-stir-fry-with-rice",
      "turkey-veggie-mini-meatballs-with-pasta",
    ]),
  },

  // ---------- Snacks & treats ----------
  {
    slug: "everyday-treats",
    status: "published",
    availability: "coming-soon",
    shelf: "snacks-and-treats",
    stage: { min: 12, max: null },
    title: "Everyday Treats",
    tagline: "Desserts with no added sugar.",
    story: "",
    forWhen: "",
    cloth: "clay",
    cover: cover("everyday-treats", 1412, "A clay-brown cloth cookbook with a gold-foil pudding cup, a banana and two soft cookies on its cover"),
    refresh: "",
    placeholderPrice: "$6.99",
    recipes: recipes([
      "banana-peanut-butter-chia-pudding",
      "chickpea-cookie-dough-fruit-dip",
      "mango-lassi-chia-pudding-cups",
      "mini-berry-yogurt-pops",
      "soft-banana-oat-toddler-cookies",
      "soft-date-almond-cocoa-bites",
      "soft-peanut-butter-oat-energy-balls",
    ]),
  },
  {
    slug: "fruit-gummies",
    status: "published",
    availability: "coming-soon",
    shelf: "snacks-and-treats",
    stage: { min: 12, max: null },
    title: "Fruit Gummies",
    tagline: "Real-fruit gummies.",
    story: "",
    forWhen: "",
    cloth: "berry",
    cover: cover("fruit-gummies", 1412, "A berry-red cloth cookbook with a gold-foil gummy mould, heart and star gummies and a strawberry on its cover"),
    refresh: "",
    placeholderPrice: "$6.99",
    recipes: [],
  },
  {
    slug: "on-the-go-snacks",
    status: "published",
    availability: "coming-soon",
    shelf: "snacks-and-treats",
    stage: TODDLER,
    title: "On-the-Go Snacks",
    tagline: "For the bag, the car and the park.",
    story: "",
    forWhen: "",
    cloth: "sky",
    cover: cover("on-the-go-snacks", 1412, "A blue cloth cookbook with a gold-foil snack tin of mini muffins, a drawstring bag and a water bottle on its cover"),
    refresh: "",
    placeholderPrice: "$6.99",
    recipes: recipes([
      "cheesy-broccoli-and-quinoa-bites",
      "savory-corn-and-cheddar-muffins",
      "cheesy-veggie-quinoa-toddler-bites",
      "cheesy-veggie-mini-muffins",
      "soft-banana-oat-toddler-cookies",
      "veggie-rice-snack-fritters",
    ]),
  },

  // ---------- Seasons & parties ----------
  {
    slug: "halloween",
    status: "published",
    availability: "open",
    inShowroom: true,
    shelf: "seasons-and-parties",
    stage: ALL_STAGES,
    title: "Halloween",
    tagline: "A festive table for little hands. Nothing scary.",
    story:
      "Pumpkin, cocoa and berries: the colours of the season, in food a toddler can hold. Gnocchi pillows for dinner, snack fries for the walk around the block, yogurt pops for after.",
    forWhen: "For the week the costumes come out, and the party where you said you'd bring something.",
    cloth: "ember",
    cover: cover("halloween", 1412, "A pumpkin-orange cloth cookbook with a gold-foil pumpkin on its cover"),
    refresh: "New recipes join each October, before the costumes come out.",
    placeholderPrice: "$6.99",
    recipes: recipes([
      "pumpkin-and-ricotta-gnocchi-pillows",
      "cinnamon-sweet-potato-snack-fries-with-yogurt-dip",
      "mini-berry-yogurt-pops",
      "spinach-and-cheese-pizza-scrolls",
      "soft-date-almond-cocoa-bites",
      "savory-corn-and-cheddar-muffins",
      "soft-banana-oat-toddler-cookies",
      "apple-sunflower-snack-rounds",
    ]),
  },
  {
    slug: "thanksgiving-table",
    status: "published",
    availability: "coming-soon",
    shelf: "seasons-and-parties",
    stage: ALL_STAGES,
    title: "Thanksgiving Table",
    tagline: "A seat at the big table, with food they can eat.",
    story: "",
    forWhen: "",
    cloth: "rust",
    cover: cover("thanksgiving-table", 1412, "A rust-orange cloth cookbook with a gold-foil roast turkey, a pumpkin and an ear of corn on its cover"),
    refresh: "",
    placeholderPrice: "$6.99",
    recipes: recipes([
      "mini-turkey-and-apple-meatloaf-muffins",
      "pumpkin-and-ricotta-gnocchi-pillows",
      "savory-corn-and-cheddar-muffins",
      "cinnamon-sweet-potato-snack-fries-with-yogurt-dip",
    ]),
  },
  {
    slug: "holiday-baking",
    status: "published",
    availability: "coming-soon",
    shelf: "seasons-and-parties",
    stage: ALL_STAGES,
    title: "Holiday Baking",
    tagline: "December baking little hands can help with.",
    story: "",
    forWhen: "",
    cloth: "crimson",
    cover: cover("holiday-baking", 1412, "A crimson cloth cookbook with a gold-foil rolling pin, star and tree cookies, a cookie cutter and holly on its cover"),
    refresh: "",
    placeholderPrice: "$6.99",
    recipes: recipes(["soft-date-almond-cocoa-bites"]),
  },
  {
    slug: "birthday-party",
    status: "published",
    availability: "coming-soon",
    shelf: "seasons-and-parties",
    stage: ALL_STAGES,
    title: "Birthday Party",
    tagline: "Party food for small guests. No nuts.",
    story: "",
    forWhen: "",
    cloth: "teal",
    cover: cover("birthday-party", 1412, "A teal cloth cookbook with a gold-foil birthday cake, a party hat and two balloons on its cover"),
    refresh: "",
    placeholderPrice: "$6.99",
    recipes: recipes(["baked-samosa-puffs", "mini-baked-chicken-nuggets", "spinach-and-cheese-pizza-scrolls", "mini-berry-yogurt-pops"]),
  },
];
