-- Phase 5: apply the external AI review (OpenAI GPT-6 via Codex, 2026-09-26) to the three
-- live free recipes. Two were rejected for choking risks (whole peas, whole blueberries).
-- Also: times that include cooling, a salmon temperature, a named oil and flour, safer
-- storage, and summaries without unsupported nutrition claims.
-- allergen_review_state stays 'unknown': an AI check is not a human review.
-- Only touches these three IDs, so it is a no-op on fresh databases.

-- Sweet Potato & Spinach Frittata Fingers
UPDATE public.recipe_catalog SET public_summary = 'Soft-baked egg and spinach frittata, cooled and cut into strips your child can hold.', total_minutes = 40, updated_at = now() WHERE id = '0003c4cc-b2cb-4e49-97c8-f4febfed39f9';
UPDATE public.recipe_bodies SET content_version = content_version + 1, ingredients = '[{"amount": "6 large", "item": "eggs"}, {"amount": "1/2 cup", "item": "sweet potato, cooked and mashed"}, {"amount": "1/2 cup", "item": "fresh spinach, finely chopped"}, {"amount": "2 tbsp", "item": "milk (dairy or breastmilk)"}, {"amount": "1/4 cup", "item": "mild cheddar cheese, shredded"}]'::jsonb, instructions = '["Preheat your oven to 350°F (175°C) and grease an 8x8 inch square baking dish with a little olive oil.", "In a large bowl, whisk the eggs and milk together until fully combined and slightly frothy.", "Stir in the mashed sweet potato, ensuring there are no large lumps, then fold in the finely chopped spinach and shredded cheese.", "Pour the mixture into the prepared baking dish, spreading it out evenly with a spatula.", "Bake for 18-22 minutes. The center should be firm to the touch and the edges slightly pulling away from the sides.", "Remove from oven and let cool completely in the dish for at least 15 minutes to set.", "Slice into rectangular strips (approx. 1 inch by 3 inches) suitable for your baby''s grip.", "SAFETY CHECK: Ensure the spinach is chopped very finely to prevent gagging."]'::jsonb, reviewed_notes = 'Steam the sweet potato in the microwave for 5 minutes for a quick prep hack.', storage_notes = 'Store in an airtight container in the fridge for up to 3 days. Freeze with parchment paper between layers for up to 2 months.', updated_at = now() WHERE recipe_id = '0003c4cc-b2cb-4e49-97c8-f4febfed39f9';
UPDATE public.recipes SET description = 'Soft-baked egg and spinach frittata, cooled and cut into strips your child can hold.', time_minutes = 40, ingredients = '[{"amount": "6 large", "item": "eggs"}, {"amount": "1/2 cup", "item": "sweet potato, cooked and mashed"}, {"amount": "1/2 cup", "item": "fresh spinach, finely chopped"}, {"amount": "2 tbsp", "item": "milk (dairy or breastmilk)"}, {"amount": "1/4 cup", "item": "mild cheddar cheese, shredded"}]'::jsonb, instructions = '["Preheat your oven to 350°F (175°C) and grease an 8x8 inch square baking dish with a little olive oil.", "In a large bowl, whisk the eggs and milk together until fully combined and slightly frothy.", "Stir in the mashed sweet potato, ensuring there are no large lumps, then fold in the finely chopped spinach and shredded cheese.", "Pour the mixture into the prepared baking dish, spreading it out evenly with a spatula.", "Bake for 18-22 minutes. The center should be firm to the touch and the edges slightly pulling away from the sides.", "Remove from oven and let cool completely in the dish for at least 15 minutes to set.", "Slice into rectangular strips (approx. 1 inch by 3 inches) suitable for your baby''s grip.", "SAFETY CHECK: Ensure the spinach is chopped very finely to prevent gagging."]'::jsonb, tips = ARRAY['Steam the sweet potato in the microwave for 5 minutes for a quick prep hack.']::text[], storage = 'Store in an airtight container in the fridge for up to 3 days. Freeze with parchment paper between layers for up to 2 months.' WHERE id = '0003c4cc-b2cb-4e49-97c8-f4febfed39f9';

-- Soft-Baked Blueberry & Oat Bars
UPDATE public.recipe_catalog SET public_summary = 'Soft oat bars sweetened with banana and blueberries. Check they are soft enough for your child and cut them to a size your child can manage.', total_minutes = 40, updated_at = now() WHERE id = '50663aaa-7e47-4b08-9fd8-a58b390db96d';
UPDATE public.recipe_bodies SET content_version = content_version + 1, ingredients = '[{"amount": "1.5 cups", "item": "rolled oats"}, {"amount": "2 medium", "item": "ripe bananas, mashed"}, {"amount": "1/2 cup", "item": "blueberries (fresh, or frozen and thawed), flattened or quartered lengthwise"}, {"amount": "2 tbsp", "item": "coconut oil, melted"}, {"amount": "1/2 tsp", "item": "vanilla extract"}]'::jsonb, instructions = '["Preheat oven to 350°F (175°C) and line an 8x8 inch baking pan with parchment paper, leaving some overhang for easy removal.", "Place 1 cup of oats in a blender or food processor and pulse until it resembles coarse flour.", "In a medium bowl, mix the mashed bananas, melted coconut oil, and vanilla extract until smooth.", "Stir in the oat flour and the remaining 1/2 cup of whole rolled oats until a dough forms.", "Gently fold in the flattened or quartered blueberries.", "Press the dough firmly and evenly into the prepared pan.", "Bake for 12-15 minutes until the edges are golden and the center feels set/firm to the touch.", "Cool completely in the pan before lifting out by the parchment paper and cutting into 16 small squares or bars.", "SAFETY NOTE: Whole blueberries are a choking risk for young children. Always flatten or quarter them before baking, and check each bar is soft before serving."]'::jsonb, reviewed_notes = 'Use very ripe bananas (brown spots are good!) for the best sweetness and binding texture.', storage_notes = 'Refrigerate within 2 hours of baking and use within 3 to 4 days, or freeze for up to 2 months.', updated_at = now() WHERE recipe_id = '50663aaa-7e47-4b08-9fd8-a58b390db96d';
UPDATE public.recipes SET description = 'Soft oat bars sweetened with banana and blueberries. Check they are soft enough for your child and cut them to a size your child can manage.', time_minutes = 40, ingredients = '[{"amount": "1.5 cups", "item": "rolled oats"}, {"amount": "2 medium", "item": "ripe bananas, mashed"}, {"amount": "1/2 cup", "item": "blueberries (fresh, or frozen and thawed), flattened or quartered lengthwise"}, {"amount": "2 tbsp", "item": "coconut oil, melted"}, {"amount": "1/2 tsp", "item": "vanilla extract"}]'::jsonb, instructions = '["Preheat oven to 350°F (175°C) and line an 8x8 inch baking pan with parchment paper, leaving some overhang for easy removal.", "Place 1 cup of oats in a blender or food processor and pulse until it resembles coarse flour.", "In a medium bowl, mix the mashed bananas, melted coconut oil, and vanilla extract until smooth.", "Stir in the oat flour and the remaining 1/2 cup of whole rolled oats until a dough forms.", "Gently fold in the flattened or quartered blueberries.", "Press the dough firmly and evenly into the prepared pan.", "Bake for 12-15 minutes until the edges are golden and the center feels set/firm to the touch.", "Cool completely in the pan before lifting out by the parchment paper and cutting into 16 small squares or bars.", "SAFETY NOTE: Whole blueberries are a choking risk for young children. Always flatten or quarter them before baking, and check each bar is soft before serving."]'::jsonb, tips = ARRAY['Use very ripe bananas (brown spots are good!) for the best sweetness and binding texture.']::text[], storage = 'Refrigerate within 2 hours of baking and use within 3 to 4 days, or freeze for up to 2 months.' WHERE id = '50663aaa-7e47-4b08-9fd8-a58b390db96d';

-- Salmon & Pea Fish Cakes
UPDATE public.recipe_catalog SET public_summary = 'Soft salmon and pea fish cakes, cooked through and served in pieces your child can manage.', total_minutes = 45, updated_at = now() WHERE id = 'a61d93da-4d19-4219-a131-bca2468ace88';
UPDATE public.recipe_bodies SET content_version = content_version + 1, ingredients = '[{"amount": "8 oz", "item": "fresh salmon fillet, boneless"}, {"amount": "2 medium", "item": "potatoes, peeled and cubed"}, {"amount": "1/4 cup", "item": "frozen peas, cooked until very soft"}, {"amount": "1 tsp", "item": "lemon juice"}, {"amount": "2 tbsp", "item": "wheat flour (for dusting)"}]'::jsonb, instructions = '["Boil the potatoes in water until tender (about 15 mins). Drain and mash until smooth.", "While potatoes cook, steam or pan-sear the salmon until the thickest part reaches 145°F (63°C) on a food thermometer. Remove skin.", "In a bowl, flake the salmon into small pieces, checking rigorously for any bones.", "Flatten each cooked pea with a fork, then combine the mashed potato, flaked salmon, flattened peas and lemon juice. Mix gently.", "Shape into 8 small, round patties.", "Lightly dust each patty with flour to prevent sticking.", "Heat 1 tbsp oil in a skillet over medium heat. Cook patties for 3-4 minutes per side until golden brown.", "Allow to cool. Cut into soft strips for younger babies.", "SAFETY REMINDER: Double check for bones even in ''boneless'' fillets."]'::jsonb, reviewed_notes = 'Flatten every pea before mixing: whole peas are a choking risk for babies and young toddlers.', storage_notes = 'Refrigerate for up to 2 days. Freeze cooked patties for up to 1 month.', updated_at = now() WHERE recipe_id = 'a61d93da-4d19-4219-a131-bca2468ace88';
UPDATE public.recipes SET description = 'Soft salmon and pea fish cakes, cooked through and served in pieces your child can manage.', time_minutes = 45, ingredients = '[{"amount": "8 oz", "item": "fresh salmon fillet, boneless"}, {"amount": "2 medium", "item": "potatoes, peeled and cubed"}, {"amount": "1/4 cup", "item": "frozen peas, cooked until very soft"}, {"amount": "1 tsp", "item": "lemon juice"}, {"amount": "2 tbsp", "item": "wheat flour (for dusting)"}]'::jsonb, instructions = '["Boil the potatoes in water until tender (about 15 mins). Drain and mash until smooth.", "While potatoes cook, steam or pan-sear the salmon until the thickest part reaches 145°F (63°C) on a food thermometer. Remove skin.", "In a bowl, flake the salmon into small pieces, checking rigorously for any bones.", "Flatten each cooked pea with a fork, then combine the mashed potato, flaked salmon, flattened peas and lemon juice. Mix gently.", "Shape into 8 small, round patties.", "Lightly dust each patty with flour to prevent sticking.", "Heat 1 tbsp oil in a skillet over medium heat. Cook patties for 3-4 minutes per side until golden brown.", "Allow to cool. Cut into soft strips for younger babies.", "SAFETY REMINDER: Double check for bones even in ''boneless'' fillets."]'::jsonb, tips = ARRAY['Flatten every pea before mixing: whole peas are a choking risk for babies and young toddlers.']::text[], storage = 'Refrigerate for up to 2 days. Freeze cooked patties for up to 1 month.' WHERE id = 'a61d93da-4d19-4219-a131-bca2468ace88';
